export const SAFE_TAGS = [
  "kids",
  "children",
  "family",
  "education",
  "classical",
  "folk",
  "lullabies"
] as const;

export type SafeTag = (typeof SAFE_TAGS)[number];

export const SAFE_TAG_ALIASES: Record<SafeTag, readonly string[]> = {
  kids: [
    "kid",
    "kids",
    "kid friendly",
    "kid-friendly",
    "kids music",
    "kids-music",
    "дети",
    "детский",
    "детская",
    "детское",
    "діти",
    "дитячий",
    "дитяча",
    "дитяче",
    "bola",
    "bolalar",
    "bolajon",
    "болалар",
    "болажон",
    "кӯдакон",
    "кудакон",
    "бачагон",
    "бачагона",
    "criança",
    "crianca",
    "crianças",
    "criancas",
    "infantil",
    "infanto juvenil"
  ],
  children: [
    "child",
    "children",
    "childrens",
    "children's",
    "children music",
    "children's music",
    "childrens music",
    "для детей",
    "для дітей",
    "детям",
    "дитячі",
    "bolalar uchun",
    "болалар учун",
    "барои кӯдакон",
    "барои кудакон",
    "para crianças",
    "para criancas"
  ],
  family: [
    "family",
    "family friendly",
    "family-friendly",
    "семья",
    "семейный",
    "семейная",
    "сімя",
    "сімейний",
    "сімейна",
    "oila",
    "оила",
    "оилавӣ",
    "оилави",
    "família",
    "familia",
    "familiar"
  ],
  education: [
    "education",
    "educational",
    "образование",
    "обучение",
    "освіта",
    "навчання",
    "talim",
    "ta'lim",
    "ta’lim",
    "talimiy",
    "таълим",
    "маориф",
    "таълимӣ",
    "educação",
    "educacao",
    "educativo",
    "infância",
    "infancia"
  ],
  classical: [
    "classical",
    "classical music",
    "классическая",
    "классика",
    "классик",
    "класична",
    "класика",
    "klassik",
    "klassika",
    "классикӣ",
    "clássica",
    "classica"
  ],
  folk: ["folk", "folk music", "народная", "народна", "xalq", "халқ", "халк", "халқӣ", "folclore", "folclórica", "folclorica"],
  lullabies: [
    "lullaby",
    "lullabies",
    "колыбельные",
    "колыбельная",
    "колискові",
    "колискова",
    "alla",
    "алла",
    "суруди алла",
    "canções de ninar",
    "cancoes de ninar",
    "canção de ninar",
    "cancao de ninar"
  ]
} as const;
